services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: my-rabbitMQ
    ports:
      - 15672:15672
      - 5672:5672
        
  api:
    build:
      context: ../src/Api
      dockerfile: Dockerfile
    depends_on: 
      - rabbitMQ
    restart: always
    environment:
      - RabbitMQ__URL=rabbitMQ
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    ports:
      - 8080:8080