services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: my-rabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin_password
      RABBITMQ_DEFAULT_VHOST: my_vhost  # Define your custom vhost here
    networks:
      - app-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
       
  apiRabbit:
    image: api-sample-rabbitmq
    build:
      context: ../src/API/
      dockerfile: Dockerfile
    depends_on:
      - nginx
      - rabbitMQ
    restart: always
    environment:
      - RabbitMQ__URL=rabbitMQ
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin_password
      - RabbitMQ__VHost=my_vhost
    networks:
      - app-network
 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - rabbitMQ
    restart: always
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind mount the custom nginx.conf file
 
networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_logs: